services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingenico-2d-barcode
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
